version: '3.9'

services:
  api:
    build: .
    container_name: taskmanager_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Tri21#Luc
      - DB_NAME=task_manager
      - DB_DIALECT=mysql
      - DB_PORT=3306
      - JWT_SECRET=secretoforteaqui123
      - JWT_EXPIRES_IN=1d
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Tri21#Luc
      MYSQL_DATABASE: task_manager
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
